### ISSUE TITLE
Can not install tetra-nerf

### ISSUE THREAD

**Issue by ZiyangYan** [jkulhanek/tetra-nerf#4] opened 2023-05-05 14:26 UTC
When I use pip install git+https://github.com/jkulhanek/tetra-nerf  to install the method,

it raise,
"
   raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-4gefgajf', '-DPYTHON_EXECUTABLE=/media/zyan/sandiskSSD/anaconda3/envs/nerfstudio/bin/python', '-DCMAKE_BUILD_TYPE=Release', '-DEXAMPLE_VERSION_INFO=0.1.1']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tetra-nerf
  Running setup.py clean for tetra-nerf
Failed to build tetra-nerf
ERROR: Could not build wheels for tetra-nerf, which is required to install pyproject.toml-based projects
"

how to deal with it? my nerfstudio is work and the install is correct.

**Comment by jkulhanek** [comment] 2023-05-05 14:28
Can you please clone the repository and run “cmake . && make”? Please post the output here.

**Comment by ZiyangYan** [comment] 2023-05-05 14:37
> Can you please clone the repository and run “cmake . && make”? Please post the output here.

-- The CXX compiler identification is GNU 7.5.0
CMake Error at /media/zyan/sandiskSSD/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:751 (message):
  Compiling the CUDA compiler identification source file
  "CMakeCUDACompilerId.cu" failed.

  Compiler: /usr/bin/nvcc

  Build flags:

  Id flags: --keep;--keep-dir;tmp -v



  The output was:

  255

  #$ _SPACE_=

  #$ _CUDART_=cudart

  #$ _HERE_=/usr/lib/nvidia-cuda-toolkit/bin

  #$ _THERE_=/usr/lib/nvidia-cuda-toolkit/bin

  #$ _TARGET_SIZE_=

  #$ _TARGET_DIR_=

  #$ _TARGET_SIZE_=64

  #$ NVVMIR_LIBRARY_DIR=/usr/lib/nvidia-cuda-toolkit/libdevice

  #$
  PATH=/usr/lib/nvidia-cuda-toolkit/bin:/media/zyan/sandiskSSD/anaconda3/envs/nerfstudio/bin:/media/zyan/sandiskSSD/anaconda3/condabin:/usr/local/cuda-11.6/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin


  #$ LIBRARIES= -L/usr/lib/x86_64-linux-gnu/stubs

  #$ rm tmp/a_dlink.reg.c

  #$ gcc -std=c++14 -D__CUDA_ARCH__=300 -E -x c++
  -DCUDA_DOUBLE_MATH_FUNCTIONS -D__CUDACC__ -D__NVCC__
  -D"__CUDACC_VER_BUILD__=85" -D"__CUDACC_VER_MINOR__=1"
  -D"__CUDACC_VER_MAJOR__=9" -include "cuda_runtime.h" -m64
  "CMakeCUDACompilerId.cu" > "tmp/CMakeCUDACompilerId.cpp1.ii"

  #$ cicc --c++14 --gnu_version=70500 --allow_managed -arch compute_30 -m64
  -ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 --include_file_name
  "CMakeCUDACompilerId.fatbin.c" -tused -nvvmir-library
  "/usr/lib/nvidia-cuda-toolkit/libdevice/libdevice.10.bc"
  --gen_module_id_file --module_id_file_name
  "tmp/CMakeCUDACompilerId.module_id" --orig_src_file_name
  "CMakeCUDACompilerId.cu" --gen_c_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.c" --stub_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.stub.c" --gen_device_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.gpu" "tmp/CMakeCUDACompilerId.cpp1.ii" -o
  "tmp/CMakeCUDACompilerId.ptx"

  #$ ptxas -arch=sm_30 -m64 "tmp/CMakeCUDACompilerId.ptx" -o
  "tmp/CMakeCUDACompilerId.sm_30.cubin"

  ptxas fatal : Value 'sm_30' is not defined for option 'gpu-name'

  # --error 0xff --





Call Stack (most recent call first):
  /media/zyan/sandiskSSD/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /media/zyan/sandiskSSD/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:53 (__determine_compiler_id_test)
  /media/zyan/sandiskSSD/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:307 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)

**Comment by ZiyangYan** [comment] 2023-05-05 14:38
> Can you please clone the repository and run “cmake . && make”? Please post the output here.

-- The CXX compiler identification is GNU 7.5.0
CMake Error at /media/zyan/sandiskSSD/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:751 (message):
  Compiling the CUDA compiler identification source file
  "CMakeCUDACompilerId.cu" failed.

  Compiler: /usr/bin/nvcc

  Build flags:

  Id flags: --keep;--keep-dir;tmp -v



  The output was:

  255

  #$ _SPACE_=

  #$ _CUDART_=cudart

  #$ _HERE_=/usr/lib/nvidia-cuda-toolkit/bin

  #$ _THERE_=/usr/lib/nvidia-cuda-toolkit/bin

  #$ _TARGET_SIZE_=

  #$ _TARGET_DIR_=

  #$ _TARGET_SIZE_=64

  #$ NVVMIR_LIBRARY_DIR=/usr/lib/nvidia-cuda-toolkit/libdevice

  #$
  PATH=/usr/lib/nvidia-cuda-toolkit/bin:/media/zyan/sandiskSSD/anaconda3/envs/nerfstudio/bin:/media/zyan/sandiskSSD/anaconda3/condabin:/usr/local/cuda-11.6/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin


  #$ LIBRARIES= -L/usr/lib/x86_64-linux-gnu/stubs

  #$ rm tmp/a_dlink.reg.c

  #$ gcc -std=c++14 -D__CUDA_ARCH__=300 -E -x c++
  -DCUDA_DOUBLE_MATH_FUNCTIONS -D__CUDACC__ -D__NVCC__
  -D"__CUDACC_VER_BUILD__=85" -D"__CUDACC_VER_MINOR__=1"
  -D"__CUDACC_VER_MAJOR__=9" -include "cuda_runtime.h" -m64
  "CMakeCUDACompilerId.cu" > "tmp/CMakeCUDACompilerId.cpp1.ii"

  #$ cicc --c++14 --gnu_version=70500 --allow_managed -arch compute_30 -m64
  -ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 --include_file_name
  "CMakeCUDACompilerId.fatbin.c" -tused -nvvmir-library
  "/usr/lib/nvidia-cuda-toolkit/libdevice/libdevice.10.bc"
  --gen_module_id_file --module_id_file_name
  "tmp/CMakeCUDACompilerId.module_id" --orig_src_file_name
  "CMakeCUDACompilerId.cu" --gen_c_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.c" --stub_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.stub.c" --gen_device_file_name
  "tmp/CMakeCUDACompilerId.cudafe1.gpu" "tmp/CMakeCUDACompilerId.cpp1.ii" -o
  "tmp/CMakeCUDACompilerId.ptx"

  #$ ptxas -arch=sm_30 -m64 "tmp/CMakeCUDACompilerId.ptx" -o
  "tmp/CMakeCUDACompilerId.sm_30.cubin"

  ptxas fatal : Value 'sm_30' is not defined for option 'gpu-name'

  # --error 0xff --





Call Stack (most recent call first):
  /media/zyan/sandiskSSD/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /media/zyan/sandiskSSD/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:53 (__determine_compiler_id_test)
  /media/zyan/sandiskSSD/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineCUDACompiler.cmake:307 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)


-- Configuring incomplete, errors occurred!

**Comment by ZiyangYan** [comment] 2023-05-05 14:43
> Can you please clone the repository and run “cmake . && make”? Please post the output here.

Do it need to finish the configuration of cmakelist and then try?

**Comment by jkulhanek** [comment] 2023-05-05 14:49
Something is wrong with your cuda installation. It also looks like you have multiple cudas installed? When installing nerfstudio, did tinycudann install without problems? What is the output of ncvv —version?

**Comment by jkulhanek** [comment] 2023-05-05 14:58
Did tinycudann install without problems?

**Comment by ZiyangYan** [comment] 2023-05-05 15:00
with torch == 1.12.1 I can install tinycudann without problem, with higher version torch, it will has problems, but now I use 1.12.1

**Comment by ZiyangYan** [comment] 2023-05-05 15:01
> with torch == 1.12.1 I can install tinycudann without problem, with higher version torch, it will has problems, but now I use 1.12.1



> Did tinycudann install without problems?

with torch == 1.12.1 I can install tinycudann without problem, with higher version torch, it will has problems, but now I use 1.12.1

**Comment by jkulhanek** [comment] 2023-05-05 15:03
How can you use torch 1.12 with cuda 11.6? Please make sure pytorch cuda version matches your installed cuda

**Comment by ZiyangYan** [comment] 2023-05-05 15:11
> How can you use torch 1.12 with cuda 11.6? Please make sure pytorch cuda version matches your installed cuda

![1683299421759](https://user-images.githubusercontent.com/92861079/236497322-3cf41be8-5733-4651-95ce-6c1672684217.png)
I think torch 1.12 also support cuda 11.6?

**Comment by jkulhanek** [comment] 2023-05-05 15:18
Ok, I didn’t know. I have no idea what is wrong with your setup. I it is not too much hassle, can you use the dockerfile instead?

**Comment by ZiyangYan** [comment] 2023-05-05 15:54
> How can you use torch 1.12 with cuda 11.6? Please make sure pytorch cuda version matches your installed cuda
I create a clean env for nerfstudio with torch 1.13.1 and install the tiny-nn successfully, but when I install tetra-nerf, I has the same problem, I will try to use dockerfile, thanks

**Comment by ZiyangYan** [comment] 2023-05-05 15:54
> How can you use torch 1.12 with cuda 11.6? Please make sure pytorch cuda version matches your installed cuda


I create a clean env for nerfstudio with torch 1.13.1 and install the tiny-nn successfully, but when I install tetra-nerf, I has the same problem, I will try to use dockerfile, thanks

**Comment by ZiyangYan** [comment] 2023-05-05 21:21
> Ok, I didn’t know. I have no idea what is wrong with your setup. I it is not too much hassle, can you use the dockerfile instead?

Hi, I use " docker build -t tetra-nerf:latest --build-context optix=/home/zyan/Downloads/NVIDIA-OptiX-SDK-7.5.0-linux64-x86_64 ." to install image but failed.

**The output is:**
[+] Building 15.1s (9/15)                                                       
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 2.48kB                                     0.0s
 => [internal] load metadata for docker.io/nvidia/cuda:11.6.1-devel-ubunt  4.5s
 => [context optix] load .dockerignore                                     0.0s
 => => transferring optix: 2B                                              0.0s
 => [context optix] load from client                                       0.0s
 => => transferring optix: 35.18kB                                         0.0s
 => [internal] load build context                                          0.0s
 => => transferring context: 3.69kB                                        0.0s
 => [stage-0 1/9] FROM docker.io/nvidia/cuda:11.6.1-devel-ubuntu18.04@sha  0.0s
 => CACHED [stage-0 2/9] COPY --from=optix . /home/zyan/Downloads/NVIDIA-  0.0s
 => ERROR [stage-0 3/9] RUN if [ ! -e /home/zyan/Downloads/NVIDIA-OptiX-  10.5s
------                                                                          
 > [stage-0 3/9] RUN if [ ! -e /home/zyan/Downloads/NVIDIA-OptiX-SDK-7.5.0-linux64-x86_64/include/optix.h ]; then echo "Could not find the OptiX library. Please install the Optix SDK and add the following argument to the buildx command: --build-context optix=/path/to/the/SDK"; exit 1; fi &&     apt-get update && apt-get install -y --no-install-recommends     ca-certificates     cmake     git     colmap     ffmpeg     python3     python3-pip     python3-dev     python-is-python3     libcgal-dev     &&     rm -rf /var/lib/apt/lists/*:
#0 0.433 Get:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease [1581 B]
#0 0.466 Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
#0 0.467 Get:3 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
#0 0.599 Get:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Packages [1257 kB]
#0 0.664 Get:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
#0 0.707 Get:6 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [83.3 kB]
#0 0.776 Get:7 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [23.8 kB]
#0 0.815 Get:8 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1623 kB]
#0 0.950 Get:9 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
#0 1.030 Get:10 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [1588 kB]
#0 1.032 Get:11 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
#0 1.036 Get:12 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
#0 1.124 Get:13 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [3296 kB]
#0 6.550 Get:14 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
#0 6.943 Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2395 kB]
#0 7.390 Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [30.8 kB]
#0 7.391 Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [3717 kB]
#0 7.747 Get:18 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [1629 kB]
#0 7.931 Get:19 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [64.0 kB]
#0 8.046 Get:20 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [20.6 kB]
#0 8.101 Fetched 29.0 MB in 8s (3760 kB/s)
#0 8.101 Reading package lists...
#0 9.185 Reading package lists...
#0 10.23 Building dependency tree...
#0 10.39 Reading state information...
#0 10.41 E: Unable to locate package python-is-python3
------
Dockerfile:12
--------------------
  11 |     COPY --from=optix . /home/zyan/Downloads/NVIDIA-OptiX-SDK-7.5.0-linux64-x86_64
  12 | >>> RUN if [ ! -e /home/zyan/Downloads/NVIDIA-OptiX-SDK-7.5.0-linux64-x86_64/include/optix.h ]; then echo "Could not find the OptiX library. Please install the Optix SDK and add the following argument to the buildx command: --build-context optix=/path/to/the/SDK"; exit 1; fi && \
  13 | >>>     apt-get update && apt-get install -y --no-install-recommends \
  14 | >>>     ca-certificates \
  15 | >>>     cmake \
  16 | >>>     git \
  17 | >>>     colmap \
  18 | >>>     ffmpeg \
  19 | >>>     python3 \
  20 | >>>     python3-pip \
  21 | >>>     python3-dev \
  22 | >>>     python-is-python3 \
  23 | >>>     libcgal-dev \
  24 | >>>     && \
  25 | >>>     rm -rf /var/lib/apt/lists/*
  26 |     
--------------------
error: failed to solve: process "/bin/sh -c if [ ! -e /home/zyan/Downloads/NVIDIA-OptiX-SDK-7.5.0-linux64-x86_64/include/optix.h ]; then echo \"Could not find the OptiX library. Please install the Optix SDK and add the following argument to the buildx command: --build-context optix=/path/to/the/SDK\"; exit 1; fi &&     apt-get update && apt-get install -y --no-install-recommends     ca-certificates     cmake     git     colmap     ffmpeg     python3     python3-pip     python3-dev     python-is-python3     libcgal-dev     &&     rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100

-------------------------------------------------------------------------------------------------------------------------------------

![1683321648109](https://user-images.githubusercontent.com/92861079/236570732-d3b555c3-80d4-4183-aafb-75d69566b856.png)
however, I can install the optix is this path, what happen for it?

**Comment by ZiyangYan** [comment] 2023-05-05 21:23
> Ok, I didn’t know. I have no idea what is wrong with your setup. I it is not too much hassle, can you use the dockerfile instead?

Hi, I use " docker build -t tetra-nerf:latest --build-context optix=/home/zyan/Downloads/NVIDIA-OptiX-SDK-7.5.0-linux64-x86_64 ." to install image but failed.

The output is:
[+] Building 15.1s (9/15)
=> [internal] load .dockerignore 0.0s
=> => transferring context: 2B 0.0s
=> [internal] load build definition from Dockerfile 0.0s
=> => transferring dockerfile: 2.48kB 0.0s
=> [internal] load metadata for docker.io/nvidia/cuda:11.6.1-devel-ubunt 4.5s
=> [context optix] load .dockerignore 0.0s
=> => transferring optix: 2B 0.0s
=> [context optix] load from client 0.0s
=> => transferring optix: 35.18kB 0.0s
=> [internal] load build context 0.0s
=> => transferring context: 3.69kB 0.0s
=> [stage-0 1/9] FROM docker.io/nvidia/cuda:11.6.1-devel-ubuntu18.04@sha 0.0s
=> CACHED [stage-0 2/9] COPY --from=optix . /home/zyan/Downloads/NVIDIA- 0.0s
=> ERROR [stage-0 3/9] RUN if [ ! -e /home/zyan/Downloads/NVIDIA-OptiX- 10.5s
[stage-0 3/9] RUN if [ ! -e /home/zyan/Downloads/NVIDIA-OptiX-SDK-7.5.0-linux64-x86_64/include/optix.h ]; then echo "Could not find the OptiX library. Please install the Optix SDK and add the following argument to the buildx command: --build-context optix=/path/to/the/SDK"; exit 1; fi && apt-get update && apt-get install -y --no-install-recommends ca-certificates cmake git colmap ffmpeg python3 python3-pip python3-dev python-is-python3 libcgal-dev && rm -rf /var/lib/apt/lists/*:
#0 0.433 Get:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 InRelease [1581 B]
#0 0.466 Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
#0 0.467 Get:3 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
#0 0.599 Get:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 Packages [1257 kB]
#0 0.664 Get:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
#0 0.707 Get:6 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [83.3 kB]
#0 0.776 Get:7 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [23.8 kB]
#0 0.815 Get:8 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1623 kB]
#0 0.950 Get:9 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
#0 1.030 Get:10 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [1588 kB]
#0 1.032 Get:11 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
#0 1.036 Get:12 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
#0 1.124 Get:13 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [3296 kB]
#0 6.550 Get:14 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
#0 6.943 Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2395 kB]
#0 7.390 Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [30.8 kB]
#0 7.391 Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [3717 kB]
#0 7.747 Get:18 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [1629 kB]
#0 7.931 Get:19 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [64.0 kB]
#0 8.046 Get:20 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [20.6 kB]
#0 8.101 Fetched 29.0 MB in 8s (3760 kB/s)
#0 8.101 Reading package lists...
#0 9.185 Reading package lists...
#0 10.23 Building dependency tree...
#0 10.39 Reading state information...
#0 10.41 E: Unable to locate package python-is-python3

Dockerfile:12
11 | COPY --from=optix . /home/zyan/Downloads/NVIDIA-OptiX-SDK-7.5.0-linux64-x86_64
12 | >>> RUN if [ ! -e /home/zyan/Downloads/NVIDIA-OptiX-SDK-7.5.0-linux64-x86_64/include/optix.h ]; then echo "Could not find the OptiX library. Please install the Optix SDK and add the following argument to the buildx command: --build-context optix=/path/to/the/SDK"; exit 1; fi &&
13 | >>> apt-get update && apt-get install -y --no-install-recommends
14 | >>> ca-certificates
15 | >>> cmake
16 | >>> git
17 | >>> colmap
18 | >>> ffmpeg
19 | >>> python3
20 | >>> python3-pip
21 | >>> python3-dev
22 | >>> python-is-python3
23 | >>> libcgal-dev
24 | >>> &&
25 | >>> rm -rf /var/lib/apt/lists/*
26 |
error: failed to solve: process "/bin/sh -c if [ ! -e /home/zyan/Downloads/NVIDIA-OptiX-SDK-7.5.0-linux64-x86_64/include/optix.h ]; then echo "Could not find the OptiX library. Please install the Optix SDK and add the following argument to the buildx command: --build-context optix=/path/to/the/SDK"; exit 1; fi && apt-get update && apt-get install -y --no-install-recommends ca-certificates cmake git colmap ffmpeg python3 python3-pip python3-dev python-is-python3 libcgal-dev && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100

![1683321795138](https://user-images.githubusercontent.com/92861079/236571114-859d0ee1-b932-42e2-93b5-0f5148aa3d6f.png)

however, I have installed the optix is this path, what happen for it?

**Comment by jkulhanek** [comment] 2023-05-05 21:45
I believe the error is  "E: Unable to locate package python-is-python3". I am not sure why the dockerfile compiles fine on my side.

**Comment by jkulhanek** [comment] 2023-05-05 21:51
I am trying now with disabled cache to see if something changed.

**Comment by jkulhanek** [comment] 2023-05-05 21:59
Ok, I tried again from scratch, and it worked. I don't understand why it does not work for you.

**Comment by jkulhanek** [comment] 2023-05-28 19:19
Please reopen if still experiencing issues.

**Comment by ZiyangYan** [comment] 2023-05-28 19:44
> Please reopen if still experiencing issues.

I asked my several colleagues to try again in different PC, including windows and different version ubuntu, they met the same problem like me.

**Comment by jkulhanek** [comment] 2023-05-29 07:46
Have you tried the newer docker image?

**Comment by jkulhanek** [comment] 2023-05-29 07:48
Also, did you modify the dockerfile in any way?

**Comment by ZiyangYan** [comment] 2023-05-29 18:12
> Have you tried the newer docker image?

Not yet, I am so busy recently, I will try later, thank you for your response

**Comment by jkulhanek** [comment] 2023-06-21 20:28
No problem. I will close the issue for now (there have been a lot of changes since you last tried, and I cannot reproduce the error). If you experience any errors with the new image, please open a new issue (or reopen this one).

**Closed by jkulhanek** 2023-06-21 20:28 UTC
